layout_spectrum: 0.3371222918121937
typography_spectrum: 0.31348610674621225
color:
  brandStrength: 0.7987650136049321
  lightness: 0.1562304072792061
  saturation: 0.09281841292894344
  rhythmicContrast: 0.478073307108134
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sureway Marketing
content: []
title: Sureway Marketing
description: NetQube Technology Company
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
purpose:
  - type: external
    url: 'http://nqsocial.com/surewaymarketing'
    label: Fill Out This Form
