layout_spectrum: 0.8050400371229885
typography_spectrum: 0.08031829093084994
color:
  brandStrength: 0.41638987330516963
  lightness: 0.13352233619253973
  saturation: 0.0838030150318795
  rhythmicContrast: 0.23882766124017832
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sureway Marketing
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a600d6e1-47bd-49e6-a013-f5d7b90e5de5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a600d6e1-47bd-49e6-a013-f5d7b90e5de5.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Sureway Marketing
description: Creating Unlimited Income
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
purpose: []
url: 'https://thegrid.ai/sureway-marketing'
