layout_spectrum: 0.5126237802340252
typography_spectrum: 0.0386960201751035
color:
  brandStrength: 0.267799964882249
  lightness: 0.15164556285910455
  saturation: 0.23164948364645982
  rhythmicContrast: 0.293740252694115
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sureway Marketing
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a600d6e1-47bd-49e6-a013-f5d7b90e5de5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a600d6e1-47bd-49e6-a013-f5d7b90e5de5.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: NetQube
description: Technology Company
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
purpose:
  - type: internal
    label: Video-1
    item: 22cedf7d-a126-462f-9479-5de1a703f809
  - type: internal
    label: Video-2
    item: 05f339fb-4504-41be-a847-7470838e38b6
url: 'https://thegrid.ai/sureway-marketing'
