layout_spectrum: 0.32018492909517177
typography_spectrum: 0.09495628235944648
color:
  brandStrength: 0.7609401693852563
  lightness: 0.15399965674173788
  saturation: 0.23530819790576135
  rhythmicContrast: 0.014699449430653218
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sureway Marketing
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F-pfnWTE6jhY%3Fstart%3D7%26feature%3Doembed%26start%3D7&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-pfnWTE6jhY&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F-pfnWTE6jhY%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: NetQube
          url: 'https://www.youtube.com/channel/UCwk5Lg7YR5nFNWFDe9eQVsw'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords: []
      description: Uploaded by NetQube on 2017-11-05.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=-pfnWTE6jhY&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=-pfnWTE6jhY&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=-pfnWTE6jhY&feature=applinks'
          type: web
          namespace: ai
          should_fallback: 'true'
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=-pfnWTE6jhY&feature=twitter-deep-link
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=-pfnWTE6jhY&feature=twitter-deep-link
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: >-
            vnd.youtube://www.youtube.com/watch?v=-pfnWTE6jhY&feature=twitter-deep-link
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/youtube.com/watch?v=-pfnWTE6jhY
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: http/youtube.com/watch?v=-pfnWTE6jhY
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/-pfnWTE6jhY?t=7s'
      title: Logo Clean Elegant 15
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Sureway Marketing
description: NetQube Technology Company
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
purpose:
  - type: external
    url: 'http://nqsocial.com/surewaymarketing'
    label: Fill Out This Form
