layout_spectrum: 0.5635593023772656
typography_spectrum: 0.6129568592741126
color:
  brandStrength: 0.7650207344483179
  lightness: 0.15819965498982974
  saturation: 0.23055283935980336
  rhythmicContrast: 0.9202097299940294
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sureway Marketing
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a600d6e1-47bd-49e6-a013-f5d7b90e5de5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a600d6e1-47bd-49e6-a013-f5d7b90e5de5.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Sureway Marketing
description: NetQube Technology Company
github: true
author:
  name: Barry Scheurweghs
  email: surewaytolive@gmail.com
purpose:
  - type: external
    url: 'http://nqsocial.com/surewaymarketing'
    label: Contact Form
